### ISSUE TITLE
[FEAT] GPG Keys

### ISSUE THREAD

**Issue by modem7** [linuxserver/docker-github-desktop#3]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Github Desktop now offers the ability to use GPG keys to sign commits.

https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits
https://gist.github.com/xavierfoucrier/c156027fcc6ae23bcee1204199f177da

Would it be possible to have some way of easily importing GPG keys to be able to sign commits?

The request is purely "importing gpg keys to gpg in the container". The config can (and should) be done by the user.

E.g. A couple of ENV vars:
```
GPG=true/false
GPG_LOCATION=/config
GPG_KEY=mykey1,mykey2
```
This then could run something like `gpg --import mykey1` `gpg --import mykey2` 

### Reason for change

Whilst it's doable in this image to implement the GPG key(s), the process is rather cumbersome.

* Copy GPG key(s) to container
* Import GPG key(s) to GPG
* Update Github Config to reflect.

**Comment by Roxedus** [comment]
> Whilst it's doable in this image to implement the GPG key(s), the process is rather cumbersome.

Could you please expand on this, as Imagine the process is the same as on bare-metal.

**Comment by thelamer** [comment]
I am still watching this, to facilitate any kind of automated ingestion of keys we need to understand the process that achieves this in the container and how to ingest the keys (IE should it be a mount, secret, env var? )
